import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const SKILL = new URL('../skill/SKILL.md', import.meta.url);
const REFS = [
  '../skill/references/framework.md',
  '../skill/references/pillar-1-cashflow.md',
  '../skill/references/pillar-2-investment.md',
  '../skill/references/pillar-3-savings.md',
  '../skill/references/decision-rules.md',
  '../skill/references/pitfalls.md',
].map((p) => new URL(p, import.meta.url));

const OUT = new URL('../three-pillar-lens.md', import.meta.url);

const HEADER = `<!-- GENERATED by scripts/build-lens.mjs — do not edit by hand. Edit skill/ instead. -->

# Three-Pillar Personal Finance — Reasoning Lens (portable single-file)

Paste this whole file into any AI (system prompt, Custom Instructions, a Project, or a Gem).
It carries the same lens as the skill version, flattened for chatbots that cannot open
reference files on demand.

`;

function stripFrontmatter(md) {
  // remove a leading YAML block delimited by --- ... ---
  if (md.startsWith('---')) {
    const end = md.indexOf('\n---', 3);
    if (end !== -1) {
      const nl = md.indexOf('\n', end + 1);
      return nl === -1 ? '' : md.slice(nl + 1).trimStart();
    }
  }
  return md;
}

export function buildLens() {
  const skill = stripFrontmatter(readFileSync(SKILL, 'utf8').trim());
  const refs = REFS.map((u) => readFileSync(u, 'utf8').trim());
  return [HEADER.trim(), skill, ...refs].join('\n\n---\n\n') + '\n';
}

function main() {
  writeFileSync(OUT, buildLens());
  console.log('wrote three-pillar-lens.md');
}

// run main only when executed directly, not when imported by the test
if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  main();
}
